dist: xenial
language: python
sudo: false
python:
- 2.7
- 3.6
- 3.7
- 3.8
- 3.9
addons:
  apt:
    packages:
    - libzmq3-dev
  code_climate:
    repo_token: cff0747bc9e271cfb6e363047e9119e13e09df9b4fe7a20295bbac64175d40ed
install:
- pip install tox-travis
- pip install coveralls
script: tox
after_success:
- COVERALLS_PARALLEL=true coveralls
notifications:
  slack:
    secure: o8qDJR9Hf3u1bzrivk/F6XLVTrdR2Pl+2qAe1Wwso3HifZt4FuhpRaJaJyZbcZEHf8kOJ6sAJ3ETsCKwBGePT52B5M715VA2XaamzADF0mQRFfP02zRZL6xMof5xCQ7BwxBmnx/PihYNbFDOvhEKxCN6umby2818W2wUAWIqU3nIKKUK9hnXXDZ+Y8HQpMw9quCoWn3Ix+fgcKjUyFZaFy50HWSayn1E+iBPxkkNzTsTkTYFrxKhAz0pI/pDiHXBIpTZhzjJTSOd/cKj4zWzq3aYMu4oL/uhews021EtiSu22jENoJf72LGnGfb3wrEqPyaY+qTv+3LRxaYajT8zhC1brpAPUISIA1qlcx3jlZTwTyAR8K3mhC1RjfzFbnt+jk33R3hQzZvg47ES5l4Pp4OyY7++ucirpGEKb2dp89FCBQsjdVajHO+o3VItawN1tngl3Rb9ll8j9t9IZfCy2yXdDnuc5Ft+LGvK85BSaYhDBEBzbGDeSxeay651vugxq6YMsZAVqc+eXEerYLySWBkl24gS+v+ASZUT7qz/PKziGrFXizvebOmIBhnhe+Y39+hvKgtCyNp8VVzaofdZf7JtUS/eMgCHSpoQuQMh/PjcYz3rsC9Lh7oxHbtOOtrgLdJ6o7Sku8gPdZ7rawRNE/WYIaAl4eKn6jsq+XQq95A=
